/**
 * Health Check Endpoint
 *
 * Monitors:
 * - Database connectivity
 * - Cron job status (active/inactive)
 * - Recent bookings (site is processing transactions)
 *
 * Sends alert email if any check fails
 * Called by pg_cron every 15 minutes
 */

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import * as Sentry from 'https://deno.land/x/sentry/index.mjs';

Sentry.init({
  dsn: "https://127229b369d63b36820bcbf33816bad0@o4511654459801600.ingest.us.sentry.io/4511654476251136",
  environment: "production",
  tracesSampleRate: 0.2,
  sendDefaultPii: false,
  release: Deno.env.get('RELEASE_VERSION') || 'unknown'
});

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')!;

const ALERT_EMAIL = 'support@universoleappstudios.com';
const FROM_EMAIL = "CJ's Fun Time Rental <bookings@cjfuntimerentals.com>";

interface HealthStatus {
  timestamp: string;
  overall: 'healthy' | 'degraded' | 'critical';
  checks: {
    database: { status: 'pass' | 'fail'; message: string };
    cronJobs: { status: 'pass' | 'fail'; message: string; details?: any };
    recentActivity: { status: 'pass' | 'fail'; message: string };
  };
}

async function sendAlert(status: HealthStatus) {
  const subject = `🚨 CJ Funtime Rentals Health Alert - ${status.overall.toUpperCase()}`;

  const failedChecks = Object.entries(status.checks)
    .filter(([_, check]) => check.status === 'fail')
    .map(([name, check]) => `- **${name}**: ${check.message}`)
    .join('\n');

  const html = `
    <h2>Health Check Failed</h2>
    <p><strong>Status:</strong> ${status.overall}</p>
    <p><strong>Time:</strong> ${status.timestamp}</p>

    <h3>Failed Checks:</h3>
    <pre>${failedChecks}</pre>

    <h3>Full Report:</h3>
    <pre>${JSON.stringify(status.checks, null, 2)}</pre>

    <hr>
    <p><em>This alert was generated by the automated health-check system.</em></p>
  `;

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: ALERT_EMAIL,
        subject,
        html
      })
    });

    if (!res.ok) {
      console.error('Failed to send alert email:', await res.text());
    } else {
      console.log('Alert email sent successfully');
    }
  } catch (error) {
    console.error('Error sending alert email:', error);
  }
}

serve(async (req) => {
  try {
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    const status: HealthStatus = {
      timestamp: new Date().toISOString(),
      overall: 'healthy',
      checks: {
        database: { status: 'pass', message: 'Database connected' },
        cronJobs: { status: 'pass', message: 'All cron jobs active' },
        recentActivity: { status: 'pass', message: 'Recent bookings detected' }
      }
    };

    // Check 1: Database connectivity
    try {
      const { data, error } = await supabase
        .from('bookings')
        .select('id')
        .limit(1);

      if (error) throw error;

      status.checks.database = {
        status: 'pass',
        message: 'Database query successful'
      };
    } catch (error) {
      status.checks.database = {
        status: 'fail',
        message: `Database error: ${error.message}`
      };
      status.overall = 'critical';
    }

    // Check 2: Cron job status
    try {
      const { data: cronJobs, error } = await supabase.rpc('get_cron_jobs');

      if (error) throw error;

      const criticalJobs = [
        'send-pickup-reminders',
        'send-return-instructions',
        'send-mid-rental-checkins',
        'post-rental-followup'
      ];

      const inactiveJobs = cronJobs
        .filter((job: any) => criticalJobs.includes(job.jobname) && !job.active)
        .map((job: any) => job.jobname);

      if (inactiveJobs.length > 0) {
        status.checks.cronJobs = {
          status: 'fail',
          message: `Inactive cron jobs: ${inactiveJobs.join(', ')}`,
          details: cronJobs
        };
        status.overall = 'critical';
      } else {
        const activeCount = cronJobs.filter((job: any) =>
          criticalJobs.includes(job.jobname) && job.active
        ).length;

        status.checks.cronJobs = {
          status: 'pass',
          message: `All ${activeCount} critical cron jobs active`,
          details: cronJobs.filter((job: any) => criticalJobs.includes(job.jobname))
        };
      }
    } catch (error) {
      status.checks.cronJobs = {
        status: 'fail',
        message: `Failed to check cron jobs: ${error.message}`
      };
      status.overall = 'degraded';
    }

    // Check 3: Recent booking activity (last 7 days)
    try {
      const sevenDaysAgo = new Date();
      sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

      const { data, error} = await supabase
        .from('bookings')
        .select('id, created_at')
        .gte('created_at', sevenDaysAgo.toISOString())
        .not('email', 'like', '%@example.com%')
        .not('email', 'like', 'test_%')
        .order('created_at', { ascending: false })
        .limit(10);

      if (error) throw error;

      if (data && data.length > 0) {
        status.checks.recentActivity = {
          status: 'pass',
          message: `${data.length} booking(s) in last 7 days (most recent: ${new Date(data[0].created_at).toLocaleDateString()})`
        };
      } else {
        // No bookings in 7 days is unusual but not critical (could be slow season)
        status.checks.recentActivity = {
          status: 'pass',
          message: 'No bookings in last 7 days (may be normal for slow season)'
        };
      }
    } catch (error) {
      status.checks.recentActivity = {
        status: 'fail',
        message: `Failed to check recent bookings: ${error.message}`
      };
      status.overall = 'degraded';
    }

    // Send alert if not healthy
    if (status.overall !== 'healthy') {
      await sendAlert(status);
    }

    return new Response(JSON.stringify(status, null, 2), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('Health check error:', error);
    Sentry.captureException(error);
    await Sentry.flush(2000);

    const criticalStatus: HealthStatus = {
      timestamp: new Date().toISOString(),
      overall: 'critical',
      checks: {
        database: { status: 'fail', message: 'Health check crashed' },
        cronJobs: { status: 'fail', message: 'Unable to check' },
        recentActivity: { status: 'fail', message: 'Unable to check' }
      }
    };

    await sendAlert(criticalStatus);

    return new Response(JSON.stringify(criticalStatus, null, 2), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
});
